language:
- python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: OpAa3su0i4BK/p2Rsb+yJ/6tYoEfGs6pXthPByCoemfksPUzHYC4Hfac+tWWyloZzPqpLJeBPEHIQcFNCgVnRnxmyeb9/psQOgrF6+YXHbMlQq9wbyBrbzhd8wftJXbsesHEJLwzLUJPqRUesCZUQwQbPIIKMKuUlfUppvn0MB8=
  app: safe-depths-8440
  on:
    repo: AlithAnar/flasktask_project
